### ISSUE TITLE
Review and Extend Documentation on Prerequisites, Setup, and Quick Start

### ISSUE THREAD

**Issue by JangasCodingplace** [JangasCodingplace/kumon-math-app#3]
# Summary:
Review the existing documentation on prerequisites, setup, and quick start for the `kumon-math-app`. Test its clarity, ease of understanding, and completeness. If any discrepancies or improvements are identified, extend and refine the documentation accordingly.

# Background:
To ensure a smooth onboarding process for developers and contributors, it's essential that our documentation is both comprehensive and clear. This task is designed to validate the user-friendliness of our documentation by having real users test and potentially refine it.

# Objective:

- Validate the clarity and ease of understanding of the existing documentation.
- Ensure all necessary steps and prerequisites are adequately covered.
- Hands-on Testing: Follow the documentation step by step as if setting up the `kumon-math-app` for the first time. Ensure that by following the documentation, the app sets up successfully without hiccups.
- Refine and extend the documentation if gaps, ambiguities, or potential improvements are identified.

# Success Criteria:
- The documentation should be easy to follow for someone unfamiliar with the project.
- All necessary prerequisites and steps for setup and quick start should be clearly outlined.
- Users should be able to set up the `kumon-math-app` without external assistance or resources.

**Comment by Konradpina** [comment]
[Improvments_on_Getting_Started_ kumon-math-app.pdf](https://github.com/JangasCodingplace/kumon-math-app/files/12456937/Improvments_on_Getting_Started_.kumon-math-app.pdf)

**Comment by JangasCodingplace** [comment]
TODO - dump to markdown
